Laravel 8 based
P3D-Legacy/next.pokemon3d.net pull request #2
Opened 2021-01-24 15:47 UTC by mrmacgeek

Pull request as anounced of discord

2021-01-25 10:25 UTC, DanielRTRD requested changes

2021-01-25 10:25 UTC, DanielRTRD commented on app/Helpers/XenforoHelper.php
> +    const BASE_URL = 'https://pokemon3d.net/forum/api';
This should be a environment variable

2021-01-25 10:25 UTC, DanielRTRD commented on app/Helpers/GitHubHelper.php
> +                $ApiUrl = "https://api.github.com/repos/P3D-Legacy/P3D-Legacy/releases/latest";
This should also be a environment variable

2021-01-31 11:46 UTC, mrmacgeek commented on app/Helpers/GitHubHelper.php
> +                $ApiUrl = "https://api.github.com/repos/P3D-Legacy/P3D-Legacy/releases/latest";
addressed in commit #62b5ad5

2021-01-31 11:46 UTC, mrmacgeek commented on app/Helpers/XenforoHelper.php
> +    const BASE_URL = 'https://pokemon3d.net/forum/api';
addressed in commit #62b5ad5

2021-01-31 18:04 UTC, DanielRTRD requested changes

2021-01-31 18:04 UTC, dsbilling commented on .env.example
> +XENFORO_API_KEY=enuGSgamqgPxgLH_UymTp04u74KVUqEK
Key should NOT be stored in example!

2021-01-31 18:04 UTC, DanielRTRD commented on app/Helpers/XenforoHelper.php
> +        $url =  config('xenforo.base_url') . $endpoint;
Double space?

2021-01-31 18:04 UTC, DanielRTRD commented on resources/views/partials/newsbox.blade.php
> +            <a href="https://pokemon3d.net/forum/threads/{{$item['thread_id']}}" class="col-12 crystal-textbox pb-2 showoff_item">
Maybe get this URL from env/config too? At least the base url for the forum

2021-01-31 18:04 UTC, DanielRTRD commented on resources/views/partials/statistics.blade.php
> +    <a href="https://pokemon3d.net/forum/" class="col-12 showoff_item crystal-textbox pb-2 pt-2">
Maybe get this URL from env/config too? At least the base url for the forum

2021-04-07 07:06 UTC, merged